Repository jpescador/hugo-future-imperfect, pull requests merged in 2018-02, with the labels that each got.

#116 Remove duplicate inclusion of Highlight.js
  layouts/partials/footer.html
Labels: Priority: Low, Status: Review Needed, Type: Maintenance

#115 Add OpenGraph meta tags
  layouts/partials/header.html
Labels: Priority: Low, Status: Accepted, Type: Enhancement

#105 Recent posts should be a class not ID
  layouts/partials/navbar.html
  layouts/partials/sidebar.html
Labels: Priority: Low, Status: Accepted, Type: Bug

#58 Multilanguage
  README.md
  exampleSite/config.toml
  exampleSite/content/contact/_index.md
  i18n/en.toml
  i18n/fr.toml
  i18n/pl.toml
  layouts/404.html
  layouts/contact/list.html
  layouts/itemized/content-single.html
  layouts/partials/footer-category.html
  layouts/partials/language-switcher.html
  layouts/partials/navbar.html
  layouts/partials/pagination.html
  layouts/partials/share-menu.html
  layouts/partials/sidebar.html
  layouts/post/content-list.html
  layouts/post/content-single.html
  layouts/post/header.html
  layouts/taxonomy/category.terms.html
  static/css/main.css
  static/flags/Flag_NoTr.png
  static/flags/en.png
  static/flags/fr.png
  static/flags/pl.png
Labels: Priority: High, Status: In Progress, Type: Enhancement

#121 Bugfix/issue 114
  static/css/main.css
Labels: Priority: Low, Status: Accepted, Type: Bug

#112 Add the possibility to set only specific social networks to share
  exampleSite/config.toml
  layouts/partials/share-links.html
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#126 Add capability for mathjax equations
  exampleSite/config.toml
  layouts/partials/footer.html
  layouts/partials/footer_mathjax.html
Labels: Priority: Low, Status: Accepted, Type: Enhancement

#122 Implement SEO elements and Instruction on the theme (issue #113)
  README.md
  exampleSite/config.toml
  layouts/partials/header.html
  layouts/partials/seo_schema.html
Labels: Priority: Low, Status: Revision Needed, Type: Enhancement
